### ISSUE TITLE
Light Error

### ISSUE THREAD

**Issue by bezark** [wjohnston7/william-vidgameHW#1]
![image](https://github.com/wjohnston7/william-vidgameHW/assets/14988649/d873bff1-8827-4b6e-979e-bda7861cdd73)
Is this the error you were referring to?

**Comment by wjohnston7** [comment]
Yes, that is the problem I was having.

**Comment by bezark** [comment]
It looks like it's a [known bug in 4.2](https://github.com/godotengine/godot/issues/84747). Until 4.3 comes out you could try using the forward plus renderer, or using [4.2.2 rc](https://godotengine.org/article/release-candidate-godot-4-1-4-and-4-2-2-rc-3/) or [4.3 dev 5](https://godotengine.org/article/dev-snapshot-godot-4-3-dev-5/)

**Comment by bezark** [comment]
Actually you might need to wait until 4.3 dev 6
